Открывается и закрывается
htmlacademy-javascript/1748441-kekstagram-32 pull request #8
Opened 2024-07-17 08:24 UTC by genntanaka

Открывает модальное окно отдельного поста, с возможностью просмотра комментариев

---
:mortar_board: [Открывается и закрывается](https://up.htmlacademy.ru/javascript/32/user/1748441/tasks/14)

:boom: https://htmlacademy-javascript.github.io/1748441-kekstagram-32/8/

2024-07-18 14:11 UTC, craz3r requested changes

2024-07-18 14:11 UTC, craz3r commented on js/full-post.js
> +function openFullPostModal(){
Не хватает класса modal-open на body

2024-07-18 14:11 UTC, craz3r commented on js/full-post.js
> +    const result = similarPosts.filter((post) => post.id === idPost);
Используем find вместо filter тк он возвращает либо результат либо undefined в отличие от filter который всегда возвращает массив

2024-07-19 04:26 UTC, genntanaka reviewed
исправлено

2024-07-19 04:29 UTC, merged